name: PyInstaller

on: 
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        - name: build with pyinstaller
    
    - uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: bin/ffr
        
    - uses: actions/upload-artifact@v2
      with:
        name: my-exe
        path: src/dist/windows
        
    - name: Display structure of downloaded files
      run: ls -R
